spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8081}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.security.user.name=disabled
spring.security.user.password=disabled

resilience4j.ratelimiter.instances.orderLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.orderLimiter.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.orderLimiter.timeoutDuration=0